kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/yourname/go-drone-hello-world

steps:
  - name: report
    image: golang
    privileged: true
    environment:
      repo: marina-amaralsantos/drone-go-git-test
      username:
        from_secret: marina-amaralsantos
      password:
        from_secret: An6J53HDeuzEhBY3BR7cJQBNJynGu3RI
    volumes:
      - name: reports
        path: /var/reports
    commands:
      - mkdir -p /var/reports
      - go get
      - go get github.com/360EntSecGroup-Skylar/goreporter
      - goreporter -p ./ -f html -r /var/reports/

#  - name: build
#    image: golang
#    commands:
#      - go get
#      - go build -o output
#      - chmod +x output
#
#  - name: run
#    image: golang
#    commands:
#      - go get
#      - go build -o output
#      - chmod +x output
#      - ./output

volumes:
  - name: reports
    host:
      path: /home/dev/work/src/github.com/cyantarek/drone-go-git-test/reports